name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: jobtracker
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/spring-demo-app

jobs:
  build-deploy:
    runs-on: [self-hosted, springboot]
    env:
      KUBECONFIG: /home/ubuntu/.kube/config

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_REPO:latest .
        docker push $DOCKER_REPO:latest

    - name: Set up kubectl (self-managed cluster)
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Wait for Kubernetes to be ready
      run: |
        echo "Waiting for Kubernetes API..."
        for i in {1..30}; do
          if kubectl get nodes > /dev/null 2>&1; then
            echo "Kubernetes is ready."
            break
          fi
          echo "Waiting ($i)..."
          sleep 5
        done
        
    - name: Apply MongoDB Kubernetes Resources
      run: |
        kubectl apply -f k8s/mongo-pvc.yaml
        kubectl apply -f k8s/mongo-service.yaml

    - name: Apply App Deployment and Service
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
